[project]
name = "criminallawagent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.9",
    "django>=5.2.17",
    "dotenv>=0.9.9",
    "faiss-cpu>=1.15.1",
    "ipykernel>=7.3.0",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.5",
    "langchain-text-splitters>=1.1.2",
    "pymupdf>=1.28.2",
    "pypdf>=6.19.0",
    "sentence-transformers>=6.1.0",
]
